### ISSUE TITLE
Does not specify API-version

### ISSUE THREAD

**Issue by srnyx** [webbukkit/Dynmap-GriefPrevention#23]
When I try and load I get this error:
`16.11 09:03:45 [Server] WARN Plugin Dynmap-GriefPrevention v0.80 does not specify an api-version.`

**Comment by srnyx** [comment]
Does this not affect anything?
Because no one has replied...

**Comment by Shewolf1896** [comment]
I get that too and it still works perfectly fine.

**Comment by srnyx** [comment]
Alright, just making sure
